name: Scheduled production run

on:
  schedule:
    - cron:  '*/2 * * * *' # Run every hour


jobs:
  prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Install Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Run request
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Deploy
      run: |
        python main.py